name        : font-adobe-100dpi
version     : 1.0.3
release     : 2
source      :
    - http://xorg.freedesktop.org/releases/individual/font/font-adobe-100dpi-1.0.3.tar.bz2 : b2c08433eab5cb202470aa9f779efefce8d9cab2534f34f3aa4a31d05671c054
license     :
    - MIT
component   : xorg.fonts
summary     : |
    X.Org fonts: font-adobe-100dpi
description : |
    X.Org fonts: font-adobe-100dpi
builddeps  :
    - pkgconfig(fontutil)
    - bdftopcf
    - mkfontdir
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
