name       : font-adobe-100dpi
version    : 1.0.4
release    : 5
source     :
    - https://www.x.org/releases/individual/font/font-adobe-100dpi-1.0.4.tar.gz : f11f4776f53fa9663dce71b71978f3fde07a1fc87c6995623e30bf3c5d05a2a1
license    :
    - MIT
component  : xorg.fonts
summary    : |
    X.Org fonts: font-adobe-100dpi
description: |
    X.Org fonts: font-adobe-100dpi
builddeps  :
    - pkgconfig(fontutil)
    - pkgconfig(harfbuzz-icu)
    - bdftopcf
    - mkfontscale
setup      : |
    %configure --with-fontrootdir=/usr/share/fonts
build      : |
    %make
install    : |
    %make_install
